### ISSUE TITLE
Modernize the codebase

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-dom#210]
I think we should introduce transpilation as many of the other unexpected repositories. There is two reasons to do that, it is too easy to use a modern syntax and break compatibility and it is of cause nice to be able to use all of the never Node features. We should still be able to run the tests without transpilation.

**Comment by alexjeffburke** [comment]
Yeah I think there is significant value in making the new code fact but making sure we can run all the cases across as many browsers as possible. Are you thinking the same approach as Unexpected core where we transpire the test cases and run them from a build directory or actually keep the tests ES5?

**Comment by papandreou** [comment]
Alternatively we could just drop support for anything below node.js 8 and release a new major version.

**Comment by sunesimonsen** [comment]
@papandreou I think that is a bit too aggressive, but it would make sense to drop support for <6 as we will in Unexpected. That would give us most of the modern features. One thing to keep in mind is that we want to support browsers for this plugin, so I think we should do a standard babel transpilation setup, but just run the tests against the src folder.

**Comment by sunesimonsen** [comment]
Let me just take a quick stab at a transpilation setup.

**Comment by sunesimonsen** [comment]
https://github.com/unexpectedjs/unexpected-dom/pull/223

**Comment by alexjeffburke** [comment]
Funnily enough at one point I tried to get rid of all the newer syntax in the core tests so they'd run in the browser natively again but it gets tricky when you want to assert things for arrow functions etc.

Given U-dom is clean I'd also vote to keep it that way and look at a node 6+ baseline for the lib.
