### ISSUE TITLE
Allow querying by text

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-dom#284]
`queried for [first] text`

**Comment by sunesimonsen** [comment]
Think about it, it is a bit more complex than my first though. What does it mean to query by text? Maybe we are better off if we could query by an element: (https://github.com/unexpectedjs/unexpected-dom/issues/283)

```js
expect(element, 'queried for element', '<button>Safe</button>', 'to have attributes', {
  id: 'safe'
});
```

It depends a bit on the use case. I imagine that you have a pretty clear picture of what you are looking for when searching for text, as it is so open ended.

**Comment by sunesimonsen** [comment]
We already support the following:

```js
expect(element, 'to contain', { textContent: 'Three' });
expect(element, 'to contain', { textContent: /three/ });
```

So we know how to search for textContent, I would just imagine that it is expensive.

**Comment by alexjeffburke** [comment]
@sunesimonsen given that we have an alternate spelling for this already, do we need the sugar? 

Not against it mind you, but I think your question about what does it mean is a good one - especially when composed with other assertions. The advantage of the `to contain` version is it, more clearly I think, communicates it's finding an element and we already have `to have text` once you have an element in hand.

Out of interest, was it something you observed users doing that led to considering it?

**Comment by sunesimonsen** [comment]
I think I came to the same conclusion. I have a college that likes react-testing-library and this is one of the queries he uses. But I think it is mainly because the library is not powerful enough to express what he really wants. 

I'm planning on making a recipes section in unexpected-reaction, so there I can explain how to achieve common things.

I'll just close this.

**Comment by alexjeffburke** [comment]
@sunesimonsen I’ve been thinking about doing similar so if you do take that on I’d be happy to contribute to the efforts :)
