### ISSUE TITLE
Investigate why the background-image url is cut

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-dom#291]
<img width="688" alt="Screenshot 2019-10-07 at 10 38 02" src="https://user-images.githubusercontent.com/90802/66296775-99b2c080-e8ee-11e9-93f2-c54bcd9e2dec.png">

**Comment by sunesimonsen** [comment]
Style prop is

```html
<div style="background-image: url(https://www.example.com/one.png)" />
```

**Comment by papandreou** [comment]
Must be happening here: https://github.com/unexpectedjs/unexpected-dom/blob/a5f961e0ac3fb52a1e09f57d14424d6b0727cb4a/src/index.js#L106

If there are 3 or more tuples, it must re-join the rest by `:` to avoid throwing away `//www.example.com/one.png)`.

**Comment by sunesimonsen** [comment]
Thanks for finding this, this is me who have introduced this bug, so I'll also fix it again :-)
