### ISSUE TITLE
Weird output when satisfying an string against an element

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-dom#294]
<img width="799" alt="Screenshot 2019-10-25 at 10 39 18" src="https://user-images.githubusercontent.com/90802/67556623-c6027580-f713-11e9-970d-537a13029f58.png">

**Comment by alexjeffburke** [comment]
@sunesimonsen what would you say should happen here?

**Comment by papandreou** [comment]
I cannot reproduce with:

```js
const document = new jsdom.JSDOM(
  '<body><div data-test-id="insertReusableContentModalBlockList" class="blockList"><div class="searchFailure" data-test-id="search-failure">The search failed. Please try again.</div></div></body>'
).window.document;
expect(document.body.firstChild, 'to satisfy', '<div></div>');
```

![element_satisfy_string_diff](https://user-images.githubusercontent.com/373545/67619339-9f6b3a00-f7fa-11e9-9f4a-e5969ccebda7.png)

Could you share your assertion?

**Comment by papandreou** [comment]
Ah, it's when there's a text node somewhere an element with children was expected:

```js
const document = new jsdom.JSDOM('<div>foo</div>').window.document;
return expect(
  document.body.firstChild,
  'to satisfy',
  '<div><div><div>bar</div></div></div>'
);
```

![text_node_satisfied_against_element](https://user-images.githubusercontent.com/373545/67619714-0e4a9200-f7ff-11e9-997b-a118d31ca7bf.png)
